Fix --save-location bugs for collect command
This addresses 2 concerns:

1) When -s or --save-location is omitted for pegleg
   site collect command, the following error is raised:

     TypeError: '_io.TextIOWrapper' object is not subscriptable

   That is because the default kwarg for the associated option
   is sys.stdout [0] which returns an object not a path, causing
   the Click library itself to blow up. Note that this is dropped
   in master [1], which isn't correct, as there is a desire to
   use stdout as the default location for collection output.

   Thus, new logic is added to output the collected document data
   to stdout.

2) When a directory doesn't exist and -s is provided (as an example
   pegleg site -p /path/to/primary/dir collect <site_name> -s <non_existent_dir>)
   it is better to just create it via os.makedirs() than to error out
   with an exception [2].

[0] https://github.com/openstack/airship-pegleg/commit/d9692126ed7cc22798e6286b43c3e86ae0f6818a#diff-bd81bbb896486546c9e59d018a83d05d
[1] https://github.com/openstack/airship-pegleg/blob/f25b5b6593df1df22d03c94f7539379262c31a97/src/bin/pegleg/pegleg/cli.py#L72
[2] https://github.com/openstack/airship-pegleg/blob/843d1a50106e1f17f3f722e2ef1634ae442fe68f/src/bin/pegleg/pegleg/engine/site.py#L36

Change-Id: Ie1da73efa437cbdfbe6d2b7ab616a1467eb57358